### PR TITLE
feat: migrate policies from csv files into k8s crd resource

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
1. convert all traditional csv-format policies into k8s crd format.
2. modified all e2e test cases to use crd resources instead of csv policy 
3. implement some simple command-line script to automatically convert a csv policy file into k8s yaml configuration files

### CODE REVIEW

**Comment by ComradeProgrammer** [comment]
> @tangyang9464 @closetool please review

Why do I see this?Why this bot automatically call some people to review?  How to kick the bot? Sorry for the inconvenience caused by the mistaken notification

**Comment by ComradeProgrammer** [comment]
@sagilio plz review

**Comment by tangyang9464** [comment]
There may be one bot for each project :satisfied:

**Comment by hsluoyz** [comment]
> > @tangyang9464 @closetool please review
> 
> Why do I see this?Why this bot automatically call some people to review? How to kick the bot? Sorry for the inconvenience caused by the mistaken notifications.

@ComradeProgrammer that's the bot developed and deployed by our community. Its configuration is here: https://oa.casbin.com/issues

It seems that our bot has pinged the wrong guys for this repo. I will fix it by adding a new entry. Do we have other repos for cloud-native area that need to be fixed?

**Comment by ComradeProgrammer** [comment]
> > > @tangyang9464 @closetool please review
> > 
> > 
> > Why do I see this?Why this bot automatically call some people to review? How to kick the bot? Sorry for the inconvenience caused by the mistaken notifications.
> 
> @ComradeProgrammer that's the "official" bot developed and deployed by our community. Its configuration is here: https://oa.casbin.com/issues
> 
> It seems that our bot has pinged the wrong guys for this repo. I will fix it by adding a new entry. Do we have other repos for cloud-native area that need to be fixed? So I can fix together.

There are no other cloud-native repository in progress. Thank you very much.

**Review by sagilio — APPROVED** [review]

**Pull request merged**
